/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CellConfiguration"
 * 	found in "CellConfiguration.asn"
 * 	`asn1c -fcompound-names -pdu=all -D /app/asn1c_generated`
 */

#ifndef	_CellConfiguration_H_
#define	_CellConfiguration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CellConfiguration__subcarrierSpacing {
	CellConfiguration__subcarrierSpacing_kHz15	= 0,
	CellConfiguration__subcarrierSpacing_kHz30	= 1,
	CellConfiguration__subcarrierSpacing_kHz60	= 2,
	CellConfiguration__subcarrierSpacing_kHz120	= 3,
	CellConfiguration__subcarrierSpacing_kHz240	= 4
} e_CellConfiguration__subcarrierSpacing;
typedef enum CellConfiguration__duplexMode {
	CellConfiguration__duplexMode_fdd	= 0,
	CellConfiguration__duplexMode_tdd	= 1
} e_CellConfiguration__duplexMode;
typedef enum CellConfiguration__cellType {
	CellConfiguration__cellType_macro	= 0,
	CellConfiguration__cellType_micro	= 1,
	CellConfiguration__cellType_pico	= 2,
	CellConfiguration__cellType_femto	= 3
} e_CellConfiguration__cellType;

/* CellConfiguration */
typedef struct CellConfiguration {
	OCTET_STRING_t	 cellGlobalId;
	OCTET_STRING_t	 nrCellIdentity;
	long	 pci;
	long	 arfcn;
	long	 subcarrierSpacing;
	long	 bandwidth;
	long	 duplexMode;
	long	 cellType;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellConfiguration_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_subcarrierSpacing_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_duplexMode_13;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_cellType_16;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CellConfiguration;

#ifdef __cplusplus
}
#endif

#endif	/* _CellConfiguration_H_ */
#include <asn_internal.h>
