/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_CellConfiguration;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module CellConfiguration in CellConfiguration.asn */
	&asn_DEF_CellConfiguration,	
	/* From module ASN1C-UsefulInformationObjectClasses in /usr/local/share/asn1c/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

