# Base image
FROM python:3.10-slim

# Créer le dossier de travail
WORKDIR /app

# Copier les fichiers dans le conteneur
COPY . /app

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Commande par défaut
CMD ["python", "send_cell_configuration.py"]
